version: '2'

networks:
  app-tier:
    driver: bridge
  neo4j-network:
    driver: bridge

services:

  nginx:
    image: bitnami/nginx
    networks:
      - app-tier
    ports:
      - '80:8080'
      - '443:8443'
    volumes:
      - ./vhost.conf:/opt/bitnami/nginx/conf/vhosts/yourapp.conf:ro

  myapp:
    tty: true
    image: 'bitnami/node:latest'
    command: "sh -c 'npm install && npm start'"
    labels:
      kompose.service.type: nodeport
    networks:
      - app-tier
      - neo4j-network
    volumes:
      - ./api:/app

  mongodb:
    image: 'bitnami/mongodb:latest'
    ports:
      - "27017:27017"
    networks:
      - app-tier
    volumes:
      - ./data:/bitnami
    environment:
      - "MONGODB_ROOT_PASSWORD=SecretWord1a"
      - "MONGODB_USERNAME=SecretUser1a"
      - "MONGODB_PASSWORD=SecretWord1a"
      - "MONGODB_DATABASE=default"

  neo4j:
    image: 'bitnami/neo4j:latest'
    networks:
      - neo4j-network
    ports:
      - '7474:7474'
      - '7473:7473'
      - '7687:7687'
    volumes:
      - ./data:/bitnami
